### ISSUE TITLE
Website does not load

### ISSUE THREAD

**Issue by habi** [tpetillon/roofmapper#8]
With OSX 10.15.6 (19G73) neither Safari (Version 13.1.2 (15609.3.5.1.3)), Google Chrome (Version 84.0.4147.125) nor Firefox (Version 79.0) load more than the FavIcon from roofmapper.eu
Is the website down?

**Comment by tpetillon** [comment]
The machine ran out of disk space, I fixed that and restarted it. However now there are HTTP 406 errors when fetching data from the OSM API. I have to investigate why it happens.

**Comment by tpetillon** [comment]
Fixed it! (As well as a few other things.)

**Comment by habi** [comment]
Awesome!
